spring:
  application:
    name: com-just-e-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka8000.com:8000/eureka,http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka
#      defaultZone: http://localhost:8000/eureka
    #指定当前客户端在注册中心的名称
  instance:
    instance-id: com-just-e-consumer-8090

server:
  port: 8090
