spring:
  application:
    name: com-just-e-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    #指定当前客户端在注册中心的名称
  instance:
    instance-id: com-just-e-consumer-8090

server:
  port: 8090
