server:
  port: 8200

eureka:
  instance:
    hostname: eureka8200.com
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka,http://localhost:8100/eureka,http://localhost:8200/eureka
    register-with-eureka: false
    fetch-registry: false